### ISSUE TITLE
installation and fragment library

### ISSUE THREAD

**Issue by dgcovell** [volkamerlab/KinaseFocusedFragmentLibrary#35]
I have not been able to install kinfraglib because I do not know what is expected in the environment.yml file. Following the instructions for installation I get:
 
[covelld@ncias-p2883-v KINFRAGLIB]$ conda env create -f environment.yml
EnvironmentFileNotFound: '/CovellData/covell/KINFRAGLIB/environment.yml' file not found

As a non-python person, I am not sure what this file is or contains. Will I find a typical yml file at github?

My second question is how top access the fragment library. I find the fragment_library directory on github and was  hoping to 
find an ascii file of the smiles for the 7k+ fragments.
My guess is that an installed KinFragLib is need to get this data. Once in KinFragLib, will the steps for creating such a file be apparent?
In lieu of getting KinFragLib running, will I find the current fragment_library as an ascii file somewhere at github.

Thanks to you and your team for making this tool available.
Regards,
David Covell
NIH-NCI

**Comment by mbackenkoehler** [comment]
Hi David,

I think you might have used the wrong path in the environment creation. The file is located in `devtools/conda-envs/environment.yml`. Accordingly, try using `conda env create -f devtools/conda-envs/environment.yml`.

The fragment databases are part of the [KinFragLib](https://github.com/volkamerlab/KinFragLib) repository (not this one). They are the sdf files located in `data/fragment_library`.

Hope this helps,
Michael
